# Generated by Django 3.2.6 on 2021-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('SchoolId', models.AutoField(primary_key=True, serialize=False)),
                ('SchoolItem', models.CharField(max_length=100)),
            ],
        ),
    ]
